settings:
    update: true
    database: mysql

mysql:
  host: localhost
  port: 3306
  databaseName: fruithcf
  username:
  password:

sqllite:
  path: %root%/plugins/FruitHCF/db/db.sqllite
  databaseName: fruithcf
  username:
  password:

mongodb:
  host: localhost
  port: 27001
  databaseName: fruithcf
  username:
  password:

redis:
  host: localhost
  port: 6006
  databaseName: fruithcf
  username:
  password: